# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration.html
#
system-ghc: false
templates:
  params:
    author-email: acowley@gmail.com
    author-name: Anthony Cowley
    copyright: Copyright (C) 2016 Anthony Cowley
    github-username: acowley
